### ISSUE TITLE
Ruby kanban board

### ISSUE THREAD

**Issue by IamYunusAli** [ChaabaneAnas/Catalog-of-my-things#15]
- link to project kanban board [here](https://github.com/ChaabaneAnas/Catalog-of-my-things/projects/1)
- we are a group of three 
       @IamYunusAli :  Team 1
       @ChaabaneAnas: Team 2
       and @techEmprez:  Team 3

**Comment by Omar-Muhamad** [comment]
# Changes Required ♻️
### Hi @IamYunusAli, @techEmprez, and @ChaabaneAnas,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Changes Required) Aspects to improve: ♻️

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20task%20should%20be%20a%20separate%20card%20that), Please put every requirement in a separate kanban card, So you suppose to have 5 group tasks cards and 9 cards for individual tasks for each team member so you suppose to have at least 32 cards in total.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ChaabaneAnas** [comment]
Hello, @Omar-Muhamad 
**i think you should reconsider your decision:**
    it is mentioned in the requirements that we should divide the tasks to our taste, 
    and there was no mention of a minimum number of tasks.
    we tried to follow previous Microverse kanban boards.
    and even if we try to follow your suggestions, you are saying 9 for each team member 
    you are basically saying each bullet-point is a task?
    ok, how are we supposed to deal with those then?
![Screenshot from 2022-11-14 19-56-50](https://user-images.githubusercontent.com/99597333/201743558-68b37405-cedb-4293-8fe4-d0beed1c952c.png)
![Screenshot from 2022-11-14 19-56-40](https://user-images.githubusercontent.com/99597333/201743565-7c83ba8d-ad69-4acc-a633-e4dd1e26e751.png)

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi Team, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to start working on it :shipit: 
Congratulations! 🎉 

# Highlights:
- All requirements completed

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
